version: '3.7'
services:
  movie-service:
    container_name: recruitment-task_movie-service
    restart: always
    build: movie-service
    image: recruitment-task/movie-service
    links:
      - mongo
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
  auth-service:
    container_name: recruitment-task_auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: recruitment-task/auth-service
    environment:
      JWT_SECRET: ${JWT_SECRET}
  mongo:
    container_name: recruitment-task_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
