version: '3.7'
services:
  movie-service:
    container_name: recruitment-task_movie-service
    restart: always
    build:
      context: movie-service
      dockerfile: Dockerfile
    image: recruitment-task/movie-service
    ports:
      - published: ${MOVIE_SVC_PORT:-3001}
        target: 3001
    links:
      - mongo
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
      AUTH_SVC_HOST: ${AUTH_SVC_HOST}
      AUTH_SVC_PORT: ${AUTH_SVC_PORT}
  auth-service:
    container_name: recruitment-task_auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: recruitment-task/auth-service
    ports:
      - published: ${AUTH_SVC_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
  mongo:
    container_name: recruitment-task_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
