version: '3.7'
services:
  app:
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    links:
      - mongo
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
      AUTH_SVC_HOST: ${AUTH_SVC_HOST}
      AUTH_SVC_PORT: ${AUTH_SVC_PORT}
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
