version: '3.7'
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3001:3001"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
      MONGO_URI: ${MONGO_URI}
